export const key = "instances";

export default {
  ADD_INSTANCE: `${key}.ADD_INSTANCE`,
  REMOVE_INSTANCE: `${key}.REMOVE_INSTANCE`,

  SET_SELECTED_INSTANCE: `${key}.SET_SELECTED_INSTANCE`,
  CLEAR_SELECTED_INSTANCE: `${key}.CLEAR_SELECTED_INSTANCE`
};
