export const key = "features";

export default {
  SET_LIST: `${key}.SET_LIST`,

  FETCH_LIST_REQUEST: `${key}.FETCH_LIST_REQUEST`,
  FETCH_LIST_SUCCESS: `${key}.FETCH_LIST_SUCCESS`,
  FETCH_LIST_FAIL: `${key}.FETCH_LIST_FAIL`,

  SET_SELECTED_FEATURE: `${key}.SET_SELECTED_FEATURE`,
  CLEAR_SELECTED_FEATURE: `${key}.CLEAR_SELECTED_FEATURE`
};
