export const key = "featureProps";

export default {
  SET_FEATURE_PROPERTY: `${key}.SET_FEATURE_PROPERTY`,
  CLEAR_FEATURE_PROPERTY: `${key}.CLEAR_FEATURE_PROPERTY`,
  CHANGE_FEATURE_PROPERTY: `${key}.CHANGE_FEATURE_PROPERTY`
};
