export const key = "instanceProps";

export default {
  SET_INSTANCE_PROPERTY: `${key}.SET_INSTANCE_PROPERTY`,
  CLEAR_INSTANCE_PROPERTY: `${key}.CLEAR_INSTANCE_PROPERTY`,
  CHANGE_INSTANCE_PROPERTY: `${key}.CHANGE_INSTANCE_PROPERTY`
};
